on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  base-y:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Cache restore node_modules
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Cache restore build
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: dist/
          key: ${{ runner.os }}-build-${{ github.sha }}

      - run: ${{ inputs.command }}
